#!/bin/sh

# Path to the aesdsocket executable
DAEMON="/usr/bin/aesdsocket"

start() {
    # Start the daemon in the background
    echo "Starting AESD Socket Daemon"
    $DAEMON &
    echo $! > /var/run/aesdsocket.pid
}

stop() {
    # Stop the daemon by sending SIGTERM
    if [ -f /var/run/aesdsocket.pid ]; then
        PID=$(cat /var/run/aesdsocket.pid)
        echo "Stopping AESD Socket Daemon"
        kill -TERM $PID
        rm /var/run/aesdsocket.pid
    else
        echo "PID file not found. Daemon might not be running."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

